apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sertigo-issuer
spec:
  acme:
    email: emain@domain
    server: https://acme.sectigo.com/v2/OV
    externalAccountBinding:
      keyID: key-id
      keySecretRef:
        name: hmac-key
        key: secret
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
