---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@gitlab.domain:repo.git
      revision: HEAD
      directories:
      - path: charts/*/*/dev
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: git@gitlab.domain:repo.git
            helm:
              valueFiles:
                - ../values-common.yaml
                - values.yaml
  - git:
      repoURL: git@gitlab.domain:repo.git
      revision: HEAD
      directories:
      - path: resources/*/*/dev
  # syncPolicy:
  #   preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path[2]}}'
      # finalizers:
      #   - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: git@gitlab.domain:repo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
